version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: planejador_db
      POSTGRES_USER: planejador
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Backend
  backend:
    build: ./backn-odejs
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://planejador:senha123@postgres:5432/planejador_db
      API_BASE_URL: http://localhost:3333
      WEB_BASE_URL: http://localhost:5173
      PORT: 3333
      NODE_ENV: production
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    volumes:
      - ./backn-odejs:/app
      - /app/node_modules

  # Frontend
  frontend:
    build: ./front-react
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:3333

volumes:
  postgres_data: 